import {AnimalRecord} from '../models';

export const animalsRegistry: AnimalRecord[] = [
  {
    id: 'holstein_friesian',
    name: 'Holstein Friesian',
    scientificName: 'Bos taurus',
    breed: 'Cow',
    weight: '600–750 kg',
    height: '140–160 cm',
    lifespan: '15–20 years',
    origin: 'Netherlands / Germany',
    color: 'Black and white',
    temperament: 'Calm, social, gentle',
    description:
      'The Holstein Friesian cow is one of the most recognizable and widely used dairy breeds in the world. Known for its high milk production, it is a cornerstone of modern agriculture. These cows are social animals that thrive in herds and require proper care, feeding, and space to maintain health and productivity.',
    funFacts: [
      'Produces more milk than most other dairy breeds.',
      'Easily recognizable due to its black-and-white pattern.',
      'Widely used in industrial dairy farming worldwide.',
      'Can produce thousands of liters of milk per year.',
    ],
    category: 'dairy',
    image: require('../../assets/animals/holstein_friesian.png'),
    flagLocation: 'Netherlands',
  },
  {
    id: 'boer_goat',
    name: 'Boer Goat',
    scientificName: 'Capra aegagrus hircus',
    breed: 'Goat',
    weight: '90–135 kg',
    height: '60–80 cm',
    lifespan: '10–15 years',
    origin: 'South Africa',
    color: 'White body with brown head',
    temperament: 'Curious, energetic, independent',
    description:
      'Boer goats are primarily bred for meat production and are known for their fast growth and strong build. They are highly adaptable and can survive in a variety of climates, including dry and harsh environments.',
    funFacts: [
      'One of the most popular meat goat breeds globally.',
      'Highly resistant to diseases and adaptable to tough conditions.',
      'Known for rapid weight gain.',
    ],
    category: 'goat',
    image: require('../../assets/animals/boer_goat.png'),
    flagLocation: 'South Africa',
  },
  {
    id: 'merino',
    name: 'Merino',
    scientificName: 'Ovis aries',
    breed: 'Sheep',
    weight: '70–105 kg',
    height: '90–110 cm',
    lifespan: '10–12 years',
    origin: 'Spain',
    color: 'White',
    temperament: 'Calm, flock-oriented, sensitive',
    description:
      'Merino sheep are famous for producing some of the finest wool in the world. They are well adapted to different climates and are often found in large grazing groups. Their wool is soft, breathable, and highly valued in the textile industry.',
    funFacts: [
      'Produces high-quality, fine wool.',
      'Widely raised in Australia and New Zealand.',
      'Requires regular shearing to maintain health.',
      'Can survive in both hot and cold climates.',
    ],
    category: 'wool',
    image: require('../../assets/animals/merino.png'),
    flagLocation: 'Spain',
  },
  {
    id: 'large_white_yorkshire',
    name: 'Large White (Yorkshire)',
    scientificName: 'Sus scrofa domesticus',
    breed: 'Pig',
    weight: '250–350 kg',
    height: '90–110 cm',
    lifespan: '10–15 years',
    origin: 'United Kingdom',
    color: 'White / pink',
    temperament: 'Intelligent, social, adaptable',
    description:
      'The Large White pig is one of the most common breeds used in commercial farming. It is valued for its productivity, fast growth, and adaptability. Pigs are highly intelligent animals capable of learning tasks and recognizing their environment.',
    funFacts: [
      'Considered one of the most intelligent farm animals.',
      'Widely used in meat production worldwide.',
      'Has excellent reproductive efficiency.',
    ],
    category: 'pig',
    image: require('../../assets/animals/large_white_yorkshire.png'),
    flagLocation: 'United Kingdom',
  },
  {
    id: 'texas_longhorn',
    name: 'Texas Longhorn',
    scientificName: 'Bos taurus',
    breed: 'Bull',
    weight: '700–1000 kg',
    height: '150–180 cm',
    lifespan: '15–20 years',
    origin: 'United States',
    color: 'Varies (brown, white, spotted)',
    temperament: 'Hardy, alert, independent',
    description:
      'Texas Longhorn bulls are iconic symbols of ranch life in North America. They are known for their extremely long horns and ability to survive in harsh environments. Resilient and require less intensive care compared to some other cattle breeds.',
    funFacts: [
      'Horns can span over 2 meters wide.',
      'Highly resistant to diseases and drought.',
      'Played a key role in American cattle drives.',
      'Known for longevity compared to other breeds.',
    ],
    category: 'heritage',
    image: require('../../assets/animals/texas_longhorn_bull.png'),
    flagLocation: 'United States',
  },
  {
    id: 'murrah_buffalo',
    name: 'Murrah Buffalo',
    scientificName: 'Bubalus bubalis',
    breed: 'Buffalo',
    weight: '500–700 kg',
    height: '130–150 cm',
    lifespan: '18–25 years',
    origin: 'India',
    color: 'Black',
    temperament: 'Calm but strong, sometimes stubborn',
    description:
      'The Murrah buffalo is one of the most important dairy buffalo breeds, especially in South Asia. It is known for producing rich, high-fat milk used in various dairy products. Strong and well adapted to hot climates.',
    funFacts: [
      'Produces milk with higher fat content than cows.',
      'Commonly used in traditional dairy production.',
      'Loves water and mud for cooling.',
      'Highly valued in rural economies.',
    ],
    category: 'buffalo',
    image: require('../../assets/animals/murrah_buffalo.png'),
    flagLocation: 'India',
  },
  {
    id: 'anglo_nubian',
    name: 'Anglo-Nubian',
    scientificName: 'Capra aegagrus hircus',
    breed: 'Domestic Goat',
    weight: '60–100 kg',
    height: '75–90 cm',
    lifespan: '10–15 years',
    origin: 'United Kingdom',
    color: 'Black, brown, white, red, or mixed patterns',
    temperament: 'Friendly, vocal, curious',
    description:
      'The Anglo-Nubian goat is a well-known domestic breed valued for both milk and its distinctive appearance. It has long, pendulous ears and a slightly convex nose. Known for producing rich milk with a high butterfat content.',
    funFacts: [
      'Known for their long, floppy ears.',
      'Their milk is especially rich and creamy.',
      'They are often more vocal than many other goat breeds.',
      'This breed is popular on hobby farms and educational farms.',
    ],
    category: 'goat',
    image: require('../../assets/animals/anglo_nubian.png'),
    flagLocation: 'United Kingdom',
  },
  {
    id: 'suffolk_sheep',
    name: 'Suffolk Sheep',
    scientificName: 'Ovis aries',
    breed: 'Domestic Sheep',
    weight: '90–160 kg',
    height: '70–90 cm',
    lifespan: '10–12 years',
    origin: 'England',
    color: 'White wool with a black face and black legs',
    temperament: 'Calm, alert, flock-oriented',
    description:
      'Suffolk sheep are one of the most recognizable domestic sheep breeds thanks to their striking black face and legs combined with a white wool body. Mainly raised for meat production and admired for their strong build and adaptability.',
    funFacts: [
      'Easily identified by their black face and legs.',
      'Commonly used in meat production.',
      'They adapt well to different climates and farm systems.',
    ],
    category: 'wool',
    image: require('../../assets/animals/suffolk_sheep.png'),
    flagLocation: 'England',
  },
  {
    id: 'berkshire_pig',
    name: 'Berkshire Pig',
    scientificName: 'Sus scrofa domesticus',
    breed: 'Domestic Pig',
    weight: '200–280 kg',
    height: '75–95 cm',
    lifespan: '10–15 years',
    origin: 'England',
    color: 'Black with white points on the legs, face, and tail',
    temperament: 'Intelligent, active, social',
    description:
      'The Berkshire pig is a traditional domestic pig breed known for its quality meat and distinctive black coloring with white markings. Has a compact, strong body and a lively, alert expression.',
    funFacts: [
      'Considered one of the premium pork breeds.',
      'Pigs can remember places and routines very well.',
      'Berkshire pigs are known for their energetic behavior.',
      'Their color pattern makes them easy to recognize.',
    ],
    category: 'pig',
    image: require('../../assets/animals/berkshire_pig.png'),
    flagLocation: 'England',
  },
  {
    id: 'jersey_cow',
    name: 'Jersey Cow',
    scientificName: 'Bos taurus',
    breed: 'Domestic Cattle',
    weight: '400–500 kg',
    height: '120–140 cm',
    lifespan: '15–18 years',
    origin: 'Jersey Island, Channel Islands',
    color: 'Light brown, fawn, or creamy brown',
    temperament: 'Gentle, alert, docile',
    description:
      'The Jersey cow is one of the most famous dairy breeds in the world and is especially valued for producing milk with a rich butterfat content. Smaller and lighter than larger cattle breeds, making them easier to handle on family farms.',
    funFacts: [
      'Famous for rich milk used in butter and cheese production.',
      'Smaller than many other dairy breeds.',
      'Often described as one of the most elegant-looking cattle breeds.',
      'Their milk usually has a high butterfat percentage.',
    ],
    category: 'dairy',
    image: require('../../assets/animals/jersey_cow.png'),
    flagLocation: 'Jersey Island',
  },
  {
    id: 'mediterranean_water_buffalo',
    name: 'Mediterranean Water Buffalo',
    scientificName: 'Bubalus bubalis',
    breed: 'Domestic Buffalo',
    weight: '600–900 kg',
    height: '135–155 cm',
    lifespan: '18–25 years',
    origin: 'Italy',
    color: 'Dark gray to black',
    temperament: 'Calm, strong, steady',
    description:
      'The Mediterranean Water Buffalo is a powerful domestic animal best known for its role in producing milk for mozzarella and other dairy products. Has a broad body, sweeping horns, and a strong, grounded appearance.',
    funFacts: [
      'The milk is widely used to make mozzarella di bufala.',
      'Buffalo milk is richer and creamier than cow’s milk.',
      'They often enjoy standing in mud or water to regulate body temperature.',
      'Their curved horns create a very striking silhouette.',
    ],
    category: 'buffalo',
    image: require('../../assets/animals/mediterranean_water_buffalo.png'),
    flagLocation: 'Italy',
  },
  {
    id: 'bactrian_camel',
    name: 'Bactrian Camel',
    scientificName: 'Camelus bactrianus',
    breed: 'Domestic Camel',
    weight: '450–700 kg',
    height: '180–230 cm',
    lifespan: '30–40 years',
    origin: 'Central Asia',
    color: 'Dark brown, sandy brown, or beige',
    temperament: 'Hardy, independent, patient',
    description:
      'The Bactrian camel is a domesticated two-humped camel that has long been used for transport, milk, wool, and work in dry and cold regions of Central Asia. Remarkable for surviving harsh environments with extreme temperature changes.',
    funFacts: [
      'Has two humps, unlike the one-humped dromedary camel.',
      'Can survive in both heat and cold.',
      'Used for transport and carrying goods for centuries.',
      'Produces milk and wool in some regions.',
      'Can go long periods with limited water.',
    ],
    category: 'camel',
    image: require('../../assets/animals/bactrian_camel.png'),
    flagLocation: 'Central Asia',
  },
  {
    id: 'dorper',
    name: 'Dorper',
    scientificName: 'Ovis aries',
    breed: 'Domestic Sheep',
    weight: '60–120 kg',
    height: '60–80 cm',
    lifespan: '10–12 years',
    origin: 'South Africa',
    color: 'White body with black head, or all white',
    temperament: 'Hardy, calm, adaptable',
    description:
      'Dorper sheep are a highly practical domestic breed developed for meat production and survival in dry, demanding environments. Hair sheep that shed much of their coat naturally, usually not requiring the same level of shearing as wool breeds.',
    funFacts: [
      'Developed to handle dry, challenging climates.',
      'Often sheds its coat naturally.',
      'Known for strong growth and resilience.',
      'Popular in meat-focused farming systems.',
    ],
    category: 'beef',
    image: require('../../assets/animals/dorper.png'),
    flagLocation: 'South Africa',
  },
  {
    id: 'saanen_goat',
    name: 'Saanen Goat',
    scientificName: 'Capra aegagrus hircus',
    breed: 'Domestic Goat',
    weight: '60–90 kg',
    height: '75–95 cm',
    lifespan: '10–15 years',
    origin: 'Switzerland',
    color: 'White or cream',
    temperament: 'Calm, friendly, dependable',
    description:
      'The Saanen goat is one of the best-known dairy goat breeds in the world and is highly valued for its steady milk production and mild temperament. Clean, refined appearance with a pale coat and upright ears.',
    funFacts: [
      'One of the most popular dairy goat breeds worldwide.',
      'Usually has a white or cream coat.',
      'Known for consistent milk production.',
      'Often chosen for family farms and educational farms.',
      'Has a calm and manageable nature.',
    ],
    category: 'dairy',
    image: require('../../assets/animals/saanen_goat.png'),
    flagLocation: 'Switzerland',
  },
];

export const getAnimalById = (id: string) =>
  animalsRegistry.find(a => a.id === id);

export const animalCategoryFilters: Array<{key: string; label: string; test?: (category: string) => boolean}> = [
  {key: 'all', label: 'All'},
  {key: 'beef', label: 'Beef Cattle', test: c => c === 'beef' || c === 'heritage'},
  {key: 'dairy', label: 'Dairy Cattle', test: c => c === 'dairy'},
  {key: 'heritage', label: 'Heritage Beef', test: c => c === 'heritage'},
  {key: 'goat', label: 'Goats', test: c => c === 'goat'},
  {key: 'wool', label: 'Wool Sheep', test: c => c === 'wool'},
  {key: 'pig', label: 'Pigs', test: c => c === 'pig'},
  {key: 'buffalo', label: 'Buffalo', test: c => c === 'buffalo'},
];
