import {LocationRecord} from '../models';

export const locationsRegistry: LocationRecord[] = [
  {
    id: 'fairOaksFarms',
    name: 'Fair Oaks Farms',
    country: 'USA',
    city: 'Fair Oaks, Indiana',
    latitude: 41.010489,
    longitude: -87.278362,
    type: 'Dairy farm agritourism campus',
    category: 'agritourism',
    tags: ['Dairy', 'Family Trip', 'Farm Learning'],
    description:
      'Fair Oaks Farms is a large agritourism destination built around modern farming, especially dairy and pigs. It combines guided farm tours, interactive exhibits, family activities, and food experiences in one campus. For visitors, this location connects livestock, education, tourism, and hands-on discovery in a very clear way. It feels less like a simple stop and more like a full ranch-and-farm day out.',
    facts: [
      'One of the best-known agritourism farm campuses in the Midwest.',
      'Visitors can explore both dairy-focused and pig-focused experiences.',
      'The site explains how modern food production works through tours and exhibits.',
    ],
    visitInfo:
      '856 N 600 E, Fair Oaks, IN 47943. Farm tours and adventures are listed as Monday–Saturday 9:00 AM–5:00 PM CT and Sunday 10:00 AM–5:00 PM CT.',
    hours: 'Mon–Sat 9:00–17:00, Sun 10:00–17:00',
    image: require('../../assets/places/fairOaksFarms.png'),
    topPick: true,
  },
  {
    id: 'swissSheepFarm',
    name: 'Swiss Sheep Farm',
    country: 'Thailand',
    city: 'Cha-am, Phetchaburi',
    latitude: 12.816389,
    longitude: 99.941944,
    type: 'Sheep farm / themed tourist farm',
    category: 'farmPark',
    tags: ['Sheep', 'Photo Spots', 'Family Visit'],
    description:
      'Swiss Sheep Farm is a sheep-centered tourist attraction with a stylized European countryside feel. It is known for open farm scenery, animal feeding, and a very visual, photo-friendly layout. The overall atmosphere is calm, approachable, and easy for casual travelers.',
    facts: [
      'Promoted as a Swiss-style sheep farm and scenic attraction near Cha-am.',
      'Known for sheep feeding and farm-themed photo areas.',
      'Located along Phet Kasem Road in the Cha-am area.',
    ],
    visitInfo:
      'Phet Kasem Road, Cha-am 76120, Thailand. A published visitor listing shows daily 9:00 AM–7:00 PM.',
    hours: 'Daily 9:00–19:00',
    image: require('../../assets/places/swissSheepFarm.png'),
    topPick: true,
  },
  {
    id: 'sheepworldFarmPark',
    name: 'Sheepworld Farm Park',
    country: 'New Zealand',
    city: 'Warkworth / Dome Valley',
    latitude: -36.371075,
    longitude: 174.62932,
    type: 'Farm park',
    category: 'farmPark',
    tags: ['Sheep Show', 'New Zealand', 'Animal Encounters'],
    description:
      'Sheepworld Farm Park is a New Zealand farm attraction built around sheep culture, farm demonstrations, and family visits. It highlights one of the most iconic hoofed domestic animals in a country strongly associated with sheep farming. The place feels educational without becoming too technical.',
    facts: [
      'Known for farm park experiences and sheep-related demonstrations.',
      'Located at 324 State Highway 1 near Warkworth / Dome Valley.',
      'Includes animal encounters in addition to sheep-focused attractions.',
    ],
    visitInfo:
      '324 State Highway 1, Warkworth / Dome Valley, New Zealand. Farm Park opening hours are listed as daily 10:00 AM–4:00 PM, with last entry at 3:30 PM.',
    hours: 'Daily 10:00–16:00',
    image: require('../../assets/places/sheepworldFarmPark.png'),
    topPick: false,
  },
  {
    id: 'surreyDocksFarm',
    name: 'Surrey Docks Farm',
    country: 'United Kingdom',
    city: 'London',
    latitude: 51.501944,
    longitude: -0.028889,
    type: 'Working city farm',
    category: 'cityFarm',
    tags: ['City Farm', 'Goats & Sheep', 'Urban Escape'],
    description:
      'Surrey Docks Farm is a working city farm on the Thames in London. Unlike remote ranches, it shows how domestic animals and farm education can exist inside a major city. A compact urban farm visit with goats, sheep, pigs, and food-growing spaces all in one place.',
    facts: [
      'Described as a working city farm in the heart of London.',
      'Hosts goats, sheep, pigs, donkeys, and a miniature Shetland pony.',
      'Sits on the south bank of the River Thames in Rotherhithe.',
    ],
    visitInfo:
      'Surrey Docks Farm, South Wharf / Rotherhithe Street, London SE16 5ET. Open 10:00 AM–4:00 PM every day, including bank holidays; organized groups should book in advance.',
    hours: 'Daily 10:00–16:00',
    image: require('../../assets/places/surreyDocksFarm.png'),
    topPick: false,
  },
  {
    id: 'melsopFarmPark',
    name: 'Melsop Farm Park',
    country: 'United Kingdom',
    city: 'Scoulton, Norfolk',
    latitude: 52.628,
    longitude: 0.948,
    type: 'Farm park',
    category: 'farmPark',
    tags: ['Rare Breeds', 'Cattle & Goats', 'Family Farm'],
    description:
      'Melsop Farm Park is a rural family farm attraction in Norfolk with a broad mix of domestic animals, including cattle, sheep, goats, pigs, and poultry. A classic countryside stop where visitors can discover multiple cloven-hoofed farm species in one place.',
    facts: [
      'Highlights a range of animals including sheep, goats, pigs, and cattle.',
      'Mentions rare breeds, including rare cattle and sheep.',
      'A year-round family attraction in Breckland, Norfolk.',
    ],
    visitInfo:
      'Ellingham Road, Scoulton, Nr Watton, Norfolk NR9 4NT, UK. Open 10:00 AM–5:00 PM seven days a week.',
    hours: 'Daily 10:00–17:00',
    image: require('../../assets/places/melsopFarmPark.png'),
    topPick: false,
  },
  {
    id: 'heididorfFarm',
    name: 'Heididorf Alpine Farm',
    country: 'Switzerland',
    city: 'Maienfeld',
    latitude: 47.090278,
    longitude: 9.468056,
    type: 'Alpine farm / cultural farm',
    category: 'agritourism',
    tags: ['Alpine Life', 'Cows', 'Scenic Views'],
    description:
      'Heididorf Alpine Farm is a traditional Swiss alpine farm experience set in a picturesque mountain landscape. It reflects classic pastoral life with grazing cows, wooden barns, and open meadows. It feels calm, authentic, and visually iconic.',
    facts: [
      'Inspired by the famous Heidi story setting.',
      'Cows here are often decorated with traditional bells.',
      'Alpine farming relies on seasonal grazing in high-altitude pastures.',
      'The region is known for dairy production, especially cheese.',
    ],
    visitInfo: 'Open daily approx. 9:00 AM–6:00 PM, seasonal variations possible.',
    hours: 'Daily 9:00–18:00',
    image: require('../../assets/places/heididorfFarm.png'),
    topPick: true,
  },
  {
    id: 'texasLonghornRanch',
    name: 'Texas Longhorn Ranch',
    country: 'USA',
    city: 'Austin, Texas',
    latitude: 30.267153,
    longitude: -97.743057,
    type: 'Ranch',
    category: 'ranch',
    tags: ['Cattle', 'Western Style', 'Ranch Life'],
    description:
      'Texas Longhorn Ranch represents classic American ranch culture with wide open spaces and iconic longhorn cattle. A strong thematic fit for the Ranch Journey concept, bringing in powerful visuals and traditional livestock heritage.',
    facts: [
      'Texas Longhorn cattle are known for extremely wide horns.',
      'Ranching culture is deeply tied to American history.',
      'These cattle are highly resilient to harsh climates.',
      'Longhorns were crucial in early cattle drives.',
    ],
    visitInfo: 'Typically 10:00 AM–5:00 PM, varies by ranch and booking.',
    hours: 'Daily 10:00–17:00',
    image: require('../../assets/places/texasLonghornRanch.png'),
    topPick: true,
  },
  {
    id: 'agrodomeFarm',
    name: 'Agrodome Farm Experience',
    country: 'New Zealand',
    city: 'Rotorua',
    latitude: -38.136847,
    longitude: 176.249746,
    type: 'Farm park',
    category: 'farmPark',
    tags: ['Sheep Show', 'Farm Experience', 'Hands On'],
    description:
      'Agrodome is one of the most famous farm experiences in New Zealand, combining entertainment with real agricultural practices. Visitors can watch live sheep shows, learn about farming techniques, and interact with animals.',
    facts: [
      'Features sheep shearing demonstrations.',
      'Includes multiple sheep breeds from New Zealand.',
      'Visitors can feed animals directly.',
      'Combines tourism with real farming education.',
    ],
    visitInfo: 'Daily 9:00 AM–5:00 PM, shows scheduled throughout the day.',
    hours: 'Daily 9:00–17:00',
    image: require('../../assets/places/agrodomeFarm.png'),
    topPick: false,
  },
  {
    id: 'lavendelfarmDenmark',
    name: 'Lavendelgården Farm',
    country: 'Denmark',
    city: 'Copenhagen',
    latitude: 55.676098,
    longitude: 12.568337,
    type: 'Farm / agritourism',
    category: 'agritourism',
    tags: ['Goats', 'Eco Farm', 'Rural Escape'],
    description:
      'Lavendelgården is a peaceful farm environment combining livestock with natural surroundings and eco-friendly practices. Known for lavender fields, it also includes small farm animals like goats and sheep. A softer, lifestyle-focused farm experience.',
    facts: [
      'Combines agriculture with eco-tourism.',
      'Focuses on sustainable farming practices.',
      'Offers seasonal farm experiences.',
    ],
    visitInfo: 'Seasonal, typically 10:00 AM–4:00 PM.',
    hours: 'Seasonal 10:00–16:00',
    image: require('../../assets/places/lavendelfarmDenmark.png'),
    topPick: false,
  },
  {
    id: 'dutchDairyFarm',
    name: 'Dutch Dairy Experience Farm',
    country: 'Netherlands',
    city: 'Utrecht Region',
    latitude: 52.132633,
    longitude: 5.291266,
    type: 'Dairy farm',
    category: 'dairyFarm',
    tags: ['Cows', 'Cheese', 'Farm Tour'],
    description:
      'This Dutch dairy farm experience highlights one of Europe’s most famous agricultural sectors: dairy production. Visitors can explore how milk is produced, processed, and turned into cheese. It connects directly to everyday food systems.',
    facts: [
      'The Netherlands is one of the world’s largest dairy exporters.',
      'Dutch cows are known for high milk production.',
      'Cheese-making is a key cultural tradition.',
      'Farms often integrate automation technologies.',
    ],
    visitInfo: 'Usually 9:00 AM–5:00 PM, varies by farm.',
    hours: 'Daily 9:00–17:00',
    image: require('../../assets/places/dutchDairyFarm.png'),
    topPick: true,
  },
  {
    id: 'australianOutbackStation',
    name: 'Outback Cattle Station',
    country: 'Australia',
    city: 'Northern Territory',
    latitude: -23.698042,
    longitude: 133.880747,
    type: 'Cattle station (large-scale ranch)',
    category: 'ranch',
    tags: ['Cattle', 'Outback', 'Extreme Nature'],
    description:
      'Outback cattle stations are massive ranches in remote Australia, often covering huge areas of land. This location introduces a sense of scale and isolation that contrasts with smaller farms. It shows how livestock farming adapts to extreme environments.',
    facts: [
      'Some stations are larger than small countries.',
      'Cattle are often managed using helicopters or vehicles.',
      'Harsh climate requires resilient livestock.',
      'Stations are key to Australia’s beef industry.',
    ],
    visitInfo: 'Visits are usually by booking only, guided tours.',
    hours: 'By booking',
    image: require('../../assets/places/australianOutbackStation.png'),
    topPick: false,
  },
  {
    id: 'bavarianAlpsFarm',
    name: 'Bavarian Alpine Farm',
    country: 'Germany',
    city: 'Bavaria',
    latitude: 47.576,
    longitude: 10.7,
    type: 'Alpine farm',
    category: 'agritourism',
    tags: ['Cows', 'Mountains', 'Traditional'],
    description:
      'Bavarian Alpine farms represent traditional European farming with strong cultural identity. Grazing cows, wooden chalets, and mountain landscapes create a visually rich experience. Supports storytelling about tradition, seasonal farming, and rural heritage.',
    facts: [
      'Alpine cows are moved seasonally between pastures.',
      'Milk from alpine cows is used for specialty cheeses.',
      'Farming traditions are preserved over centuries.',
    ],
    visitInfo: 'Typically 8:00 AM–6:00 PM, varies by location.',
    hours: 'Daily 8:00–18:00',
    image: require('../../assets/places/bavarianAlpsFarm.png'),
    topPick: false,
  },
  {
    id: 'clarkesFarm',
    name: 'Clarke’s Farm & Home Dairy',
    country: 'United Kingdom',
    city: 'London',
    latitude: 51.588,
    longitude: -0.391,
    type: 'City farm',
    category: 'cityFarm',
    tags: ['Goats', 'Cows', 'Family Visit'],
    description:
      'Clarke’s Farm is one of the oldest working farms in London, offering a rare chance to experience traditional farm life inside a major city. Visitors can interact with cows, goats, sheep, and other domestic animals while learning about small-scale farming.',
    facts: [
      'One of the oldest city farms in London.',
      'Hosts cows, pigs, goats, and poultry.',
      'Focuses on education for children and families.',
      'Free entry makes it very accessible.',
    ],
    visitInfo: 'Typically 10:00 AM–4:30 PM, may vary by season.',
    hours: 'Daily 10:00–16:30',
    image: require('../../assets/places/clarkesFarm.png'),
    topPick: false,
  },
  {
    id: 'laFermeDeGally',
    name: 'La Ferme de Gally',
    country: 'France',
    city: "Saint-Cyr-l'École",
    latitude: 48.8049,
    longitude: 2.1156,
    type: 'Educational farm',
    category: 'educationalFarm',
    tags: ['Sheep', 'Pigs', 'Farm Learning'],
    description:
      'La Ferme de Gally is a well-known educational farm near Paris where visitors can explore traditional French agriculture. It combines livestock, gardens, and hands-on workshops. A strong cultural and educational layer.',
    facts: [
      'Offers workshops for children and families.',
      'Includes sheep, goats, pigs, and donkeys.',
      'Promotes sustainable farming practices.',
      'Close to Versailles, making it popular with tourists.',
    ],
    visitInfo: 'Usually 9:30 AM–6:00 PM, seasonal adjustments apply.',
    hours: 'Daily 9:30–18:00',
    image: require('../../assets/places/laFermeDeGally.png'),
    topPick: false,
  },
  {
    id: 'oldMacDonaldsFarm',
    name: 'Old MacDonald’s Farm & Fun Park',
    country: 'United Kingdom',
    city: 'Brentwood',
    latitude: 51.549,
    longitude: 0.175,
    type: 'Farm park',
    category: 'farmPark',
    tags: ['Family Fun', 'Farm Animals', 'Interactive'],
    description:
      'Old MacDonald’s Farm is a family-oriented farm park combining livestock encounters with entertainment activities. Visitors can see cows, sheep, goats, and pigs while enjoying a playful environment.',
    facts: [
      'Inspired by the famous children’s song.',
      'Combines animals with rides and attractions.',
      'Very popular for family day trips.',
    ],
    visitInfo: 'Typically 10:00 AM–5:00 PM, seasonal schedule.',
    hours: 'Daily 10:00–17:00',
    image: require('../../assets/places/oldMacDonaldsFarm.png'),
    topPick: false,
  },
  {
    id: 'hofGutNeuhof',
    name: 'Hofgut Neuhof',
    country: 'Germany',
    city: 'Frankfurt',
    latitude: 50.110924,
    longitude: 8.682127,
    type: 'Organic farm',
    category: 'dairyFarm',
    tags: ['Cows', 'Organic', 'Eco Farm'],
    description:
      'Hofgut Neuhof is an organic farm near Frankfurt focused on sustainable agriculture and livestock care. Offers visitors insight into eco-friendly farming methods and animal welfare.',
    facts: [
      'Focuses on organic dairy production.',
      'Promotes sustainable agriculture.',
      'Offers direct farm-to-table products.',
    ],
    visitInfo: 'Usually 8:00 AM–6:00 PM, varies by activity.',
    hours: 'Daily 8:00–18:00',
    image: require('../../assets/places/hofGutNeuhof.png'),
    topPick: false,
  },
  {
    id: 'deAnnaHoeveFarm',
    name: 'De Anna Hoeve',
    country: 'Netherlands',
    city: 'Hilversum',
    latitude: 52.229169,
    longitude: 5.166897,
    type: 'Farm / nature farm',
    category: 'agritourism',
    tags: ['Cows', 'Goats', 'Nature'],
    description:
      'De Anna Hoeve is a peaceful farm located within a natural reserve, combining livestock with forest surroundings. A quiet and scenic experience where visitors can see cows and goats in a relaxed environment.',
    facts: [
      'Located inside a nature reserve area.',
      'Combines farming with conservation.',
      'Popular for walking and cycling routes.',
    ],
    visitInfo: 'Open access area, farm activities typically daytime hours.',
    hours: 'Open access',
    image: require('../../assets/places/deAnnaHoeveFarm.png'),
    topPick: false,
  },
  {
    id: 'laGranjaBarcelona',
    name: 'La Granja Aventura Park',
    country: 'Spain',
    city: 'Barcelona',
    latitude: 41.5667,
    longitude: 2.225,
    type: 'Farm park',
    category: 'farmPark',
    tags: ['Goats', 'Sheep', 'Adventure'],
    description:
      'La Granja Aventura Park blends farm life with adventure activities and outdoor experiences. Visitors can interact with animals like goats and sheep while also enjoying climbing and nature trails.',
    facts: [
      'Mixes farm animals with adventure park elements.',
      'Focuses on outdoor experiences.',
      'Located near Barcelona, making it accessible for tourists.',
    ],
    visitInfo: 'Typically 10:00 AM–6:00 PM, varies seasonally.',
    hours: 'Daily 10:00–18:00',
    image: require('../../assets/places/laGranjaBarcelona.png'),
    topPick: false,
  },
  {
    id: 'featherdaleFarmZone',
    name: 'Featherdale Farm Experience',
    country: 'Australia',
    city: 'Sydney',
    latitude: -33.75,
    longitude: 150.85,
    type: 'Wildlife & farm mix',
    category: 'wildlifeFarm',
    tags: ['Sheep', 'Goats', 'Family'],
    description:
      'While primarily known as a wildlife park, Featherdale also includes areas with domestic farm animals like sheep and goats. A hybrid entry showing overlap between wildlife tourism and farm experiences.',
    facts: [
      'Known for Australian wildlife.',
      'Includes interactive animal zones.',
      'Popular tourist attraction near Sydney.',
    ],
    visitInfo: 'Usually 8:00 AM–5:00 PM.',
    hours: 'Daily 8:00–17:00',
    image: require('../../assets/places/featherdaleFarmZone.png'),
    topPick: false,
  },
  {
    id: 'greenMeadowsFarm',
    name: 'Green Meadows Farm',
    country: 'USA',
    city: 'Atlanta',
    latitude: 33.749,
    longitude: -84.388,
    type: 'Educational farm',
    category: 'educationalFarm',
    tags: ['Cows', 'Pigs', 'Farm Tour'],
    description:
      'Green Meadows Farm is an educational farm focused on teaching visitors about traditional agriculture. Offers guided tours, animal feeding, and demonstrations.',
    facts: [
      'Offers structured farm tours.',
      'Focuses on traditional farming methods.',
      'Visitors can interact with animals directly.',
    ],
    visitInfo: 'Usually 9:00 AM–4:00 PM, by schedule.',
    hours: 'Daily 9:00–16:00',
    image: require('../../assets/places/greenMeadowsFarm.png'),
    topPick: false,
  },
  {
    id: 'shelburneFarms',
    name: 'Shelburne Farms',
    country: 'USA',
    city: 'Shelburne, Vermont',
    latitude: 44.3806,
    longitude: -73.2279,
    type: 'Educational farm / working farm',
    category: 'educationalFarm',
    tags: ['Dairy', 'Sustainable', 'Scenic'],
    description:
      'Shelburne Farms is a historic working farm set on the shores of Lake Champlain, combining agriculture, education, and sustainability. Pastures stretch toward the water and traditional farm buildings create a timeless atmosphere.',
    facts: [
      'Produces its own well-known cheddar cheese.',
      'Operates as a nonprofit focused on education.',
      'The land covers over 1,400 acres.',
      'Visitors explore farming and conservation practices in one place.',
    ],
    visitInfo: 'Typically 9:00 AM–5:00 PM, seasonal variations depending on programs.',
    hours: 'Daily 9:00–17:00',
    image: require('../../assets/places/shelburneFarms.png'),
    topPick: false,
  },
  {
    id: 'bodnantWelshFoodFarm',
    name: 'Bodnant Welsh Food Farm',
    country: 'United Kingdom',
    city: 'Conwy, Wales',
    latitude: 53.235,
    longitude: -3.8,
    type: 'Farm / food estate',
    category: 'agritourism',
    tags: ['Cattle', 'Local Food', 'Rural Experience'],
    description:
      'Bodnant Welsh Food Farm highlights Welsh agricultural traditions and local food production. Surrounded by rolling hills, the farm offers a strong connection between livestock and regional cuisine.',
    facts: [
      'Focuses heavily on Welsh produce and culinary heritage.',
      'Located in a historically agricultural region of Wales.',
      'Connects farming with on-site food experiences.',
    ],
    visitInfo: 'Usually 10:00 AM–5:00 PM, may vary by season and events.',
    hours: 'Daily 10:00–17:00',
    image: require('../../assets/places/bodnantWelshFoodFarm.png'),
    topPick: false,
  },
  {
    id: 'fermePedagogiqueDeParis',
    name: 'Ferme Pédagogique de Paris',
    country: 'France',
    city: 'Paris',
    latitude: 48.8275,
    longitude: 2.4342,
    type: 'Educational city farm',
    category: 'educationalFarm',
    tags: ['Sheep', 'Goats', 'Education'],
    description:
      'Located within the Bois de Vincennes, this educational farm offers a rare agricultural space inside Paris. Focused on teaching visitors about traditional farming, animal care, and biodiversity with sheep, goats, cows, and other domestic animals.',
    facts: [
      'Located inside one of the largest parks in Paris.',
      'Designed primarily for educational visits.',
      'Maintains traditional farming methods.',
      'Entry is often free or low-cost.',
    ],
    visitInfo: 'Typically 10:00 AM–5:00 PM, closed on certain weekdays.',
    hours: 'Mostly 10:00–17:00',
    image: require('../../assets/places/fermePedagogiqueDeParis.png'),
    topPick: false,
  },
  {
    id: 'ranchoCortez',
    name: 'Rancho Cortez',
    country: 'USA',
    city: 'Bandera, Texas',
    latitude: 29.7233,
    longitude: -98.8334,
    type: 'Ranch',
    category: 'ranch',
    tags: ['Cattle', 'Horseback', 'Western'],
    description:
      'Rancho Cortez is a traditional Texas ranch experience that combines livestock, horseback riding, and immersive Western-style stays. Visitors can stay overnight and participate in ranch activities.',
    facts: [
      'Located in Bandera, known as the Cowboy Capital of the World.',
      'Offers horseback riding experiences.',
      'Combines tourism with working ranch operations.',
      'Visitors can stay on-site and experience ranch life.',
    ],
    visitInfo: 'Open year-round, activities typically 9:00 AM–6:00 PM, lodging available.',
    hours: 'Year-round',
    image: require('../../assets/places/ranchoCortez.png'),
    topPick: false,
  },
  {
    id: 'fermeDuBonheur',
    name: 'Ferme du Bonheur',
    country: 'France',
    city: 'Nanterre',
    latitude: 48.9,
    longitude: 2.22,
    type: 'Urban farm',
    category: 'cityFarm',
    tags: ['Goats', 'Community', 'Cultural'],
    description:
      'Ferme du Bonheur is a unique urban farm that blends agriculture with art, culture, and community events. A living social space where farming meets creativity with goats and other livestock alongside performances and workshops.',
    facts: [
      'Combines farming with cultural events.',
      'Hosts performances and community gatherings.',
      'Known for its unconventional, artistic atmosphere.',
    ],
    visitInfo: 'Variable schedule, often event-based, typically open afternoons and weekends.',
    hours: 'Event-based',
    image: require('../../assets/places/fermeDuBonheur.png'),
    topPick: false,
  },
  {
    id: 'maplewoodFarm',
    name: 'Maplewood Farm',
    country: 'Canada',
    city: 'North Vancouver',
    latitude: 49.326,
    longitude: -123.05,
    type: 'Farm park',
    category: 'farmPark',
    tags: ['Sheep', 'Goats', 'Family Friendly'],
    description:
      'Maplewood Farm is a well-established farm park offering a welcoming and accessible introduction to farm animals. A balance between structured educational experiences and relaxed exploration with sheep, goats, cows, and other animals.',
    facts: [
      'Houses a wide range of domestic farm animals.',
      'Designed to be highly accessible for families.',
      'Close to a major city while maintaining a rural feel.',
      'Offers feeding and interaction experiences.',
    ],
    visitInfo: 'Typically 10:00 AM–4:00 PM, seasonal adjustments possible.',
    hours: 'Daily 10:00–16:00',
    image: require('../../assets/places/maplewoodFarm.png'),
    topPick: false,
  },
];

export const getLocationById = (id: string) =>
  locationsRegistry.find(l => l.id === id);
